//! HPKE (RFC 9180) utilities for ISO 18013-7 Annex C / W3C DC API.
//!
//! Implements HPKE Base mode decryption using the cipher suite required by
//! ISO 18013-7 Annex C:
//! - KEM:  DHKEM(X25519, HKDF-SHA256)
//! - KDF:  HKDF-SHA256
//! - AEAD: AES-128-GCM
//!
//! ## Browser Support
//!
//! Uses the Web Crypto API (`SubtleCrypto`) which supports X25519 ECDH
//! key agreement in Chrome 113+, Edge 113+, and other Chromium browsers.
//!
//! ## References
//! - RFC 9180 (HPKE)
//! - EU Age Verification Profile Annex A, §A.5

// ============================================================================
// Types
// ============================================================================

/** COSE_Key structure for X25519 (kty: 2 = EC2, crv: 4 = X25519). */
export interface CoseKey {
    /** Key type: 1 = OKP (RFC 8037), 2 = EC2 */
    kty: number;
    /** Curve: 4 = X25519, 1 = P-256 */
    crv: number;
    /** X coordinate (public key bytes) */
    x: Uint8Array;
}

/** Parameters for HPKE decryption (Base mode). */
export interface HpkeDecryptParams {
    /** The recipient's private key (generated by generateHpkeKeyPair). */
    recipientPrivateKey: CryptoKey;
    /** The sender's ephemeral public key (from the EncryptedResponse). */
    enc: Uint8Array;
    /** The ciphertext to decrypt. */
    cipherText: Uint8Array;
}

// ============================================================================
// Constants
// ============================================================================

/** HPKE suite ID for DHKEM(X25519, HKDF-SHA256), HKDF-SHA256, AES-128-GCM */
const HPKE_SUITE_ID = new Uint8Array([
    0x4b, 0x45, 0x4d, 0x00, // "KEM\0"
    0x00, 0x20,             // KEM ID: 0x0020 = DHKEM(X25519, HKDF-SHA256)
    0x00, 0x01,             // KDF ID: 0x0001 = HKDF-SHA256
    0x00, 0x01,             // AEAD ID: 0x0001 = AES-128-GCM
]);

/** Label for HPKE "shared_secret" context creation. */
const LABEL_SHARED_SECRET = new Uint8Array([0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74]);
// "shared_secret"

/** Label for HPKE "key" derivation */
const LABEL_KEY = new Uint8Array([0x6b, 0x65, 0x79]);
// "key"

/** Label for HPKE "base_nonce" derivation */
const LABEL_BASE_NONCE = new Uint8Array([0x62, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65]);
// "base_nonce"

/** Label for HPKE "psk_id_hash" */
const LABEL_PSK_ID_HASH = new Uint8Array([0x70, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68]);
// "psk_id_hash"

/** Label for HPKE "secret" */
const LABEL_SECRET = new Uint8Array([0x73, 0x65, 0x63, 0x72, 0x65, 0x74]);
// "secret"

/** Label for HPKE "info_hash" */
const LABEL_INFO_HASH = new Uint8Array([0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73, 0x68]);
// "info_hash"

// ============================================================================
// Public API
// ============================================================================

/**
 * Generate an X25519 HPKE key pair.
 *
 * Returns the private key (as a CryptoKey) and the public key in COSE_Key
 * format for inclusion in the `encryptionInfo` CBOR blob.
 */
export async function generateHpkeKeyPair(): Promise<{
    privateKey: CryptoKey;
    publicKeyCoseKey: CoseKey;
}> {
    const keyPair = await crypto.subtle.generateKey(
        { name: "ECDH", namedCurve: "X25519" },
        true, // extractable
        ["deriveBits"],
    );

    const publicKeyRaw = await crypto.subtle.exportKey("raw", keyPair.publicKey);

    const coseKey: CoseKey = {
        kty: 1,  // OKP (Octet Key Pair)
        crv: 4,  // X25519
        x: new Uint8Array(publicKeyRaw),
    };

    return {
        privateKey: keyPair.privateKey,
        publicKeyCoseKey: coseKey,
    };
}

/**
 * HPKE Base mode decryption.
 *
 * Uses the DHKEM(X25519, HKDF-SHA256) + AES-128-GCM cipher suite
 * as required by ISO 18013-7 Annex C.
 *
 * @param params.recipientPrivateKey — The recipient's X25519 private key.
 * @param params.enc                 — The sender's ephemeral public key (raw bytes).
 * @param params.cipherText          — The ciphertext (includes 16-byte GCM tag).
 */
export async function hpkeOpen(params: HpkeDecryptParams): Promise<Uint8Array> {
    const { recipientPrivateKey, enc, cipherText } = params;

    // 1. Import the sender's ephemeral public key
    const senderPublicKey = await crypto.subtle.importKey(
        "raw",
        enc,
        { name: "ECDH", namedCurve: "X25519" },
        false,
        [],
    );

    // 2. ECDH key agreement to derive the shared secret
    const sharedSecretRaw = await crypto.subtle.deriveBits(
        {
            name: "ECDH",
            public: senderPublicKey,
        },
        recipientPrivateKey,
        256, // X25519 shared secret is 256 bits
    );

    const sharedSecret = new Uint8Array(sharedSecretRaw);

    // 3. HPKE context setup (simplified Base mode)
    //    Per RFC 9180 §5.1:
    //    - context = SetupBaseS(pkR, skR, info)
    //    - key = context.key
    //    - base_nonce = context.base_nonce
    //    - nonce = base_nonce XOR seq (seq=0 for first message)
    const info = new Uint8Array(0); // Empty info for Annex C — the DC API wrapper handles binding
    const { key, nonce } = await hpkeContextSetup(sharedSecret, info);

    // 4. AES-128-GCM decrypt
    const plaintext = await crypto.subtle.decrypt(
        {
            name: "AES-GCM",
            iv: nonce,
            tagLength: 128, // 16-byte tag
        },
        key,
        cipherText,
    );

    return new Uint8Array(plaintext);
}

// ============================================================================
// Internal HPKE helpers
// ============================================================================

/**
 * Set up the HPKE context (Base mode).
 *
 * Derives the AEAD key and nonce from the shared secret per RFC 9180 §5.1.
 */
async function hpkeContextSetup(
    sharedSecret: Uint8Array,
    info: Uint8Array,
): Promise<{ key: CryptoKey; nonce: Uint8Array }> {
    // context_id = suite_id || info_hash
    const infoHash = await sha256(info);
    const contextId = concatBuffers(HPKE_SUITE_ID, new Uint8Array(infoHash));

    // secret = Extract(psk, shared_secret), where psk is empty in Base mode
    // With empty PSK: Extract("", shared_secret) = Extract(salt="", ikm=shared_secret)
    const pskIdHash = await sha256(new Uint8Array(0));

    // HPKE labelled extract: secret = LabeledExtract("", "shared_secret", shared_secret, suite_id)
    const secret = await hkdfExtract(
        new Uint8Array(0), // empty salt
        LABEL_SHARED_SECRET,
        sharedSecret,
        new Uint8Array(0), // empty ikm_id (Base mode)
    );

    // Derive AEAD key
    const keyBytes = await hkdfExpand(secret, LABEL_KEY, contextId, 16); // AES-128 key = 16 bytes

    const key = await crypto.subtle.importKey(
        "raw",
        keyBytes,
        { name: "AES-GCM" },
        false,
        ["decrypt"],
    );

    // Derive base nonce
    const baseNonce = await hkdfExpand(secret, LABEL_BASE_NONCE, contextId, 12); // AES-GCM nonce = 12 bytes

    return { key, nonce: baseNonce };
}

/**
 * Simple HKDF Extract (no HPKE labels — just SHA-256 HMAC based).
 * For the labelled extract in HPKE, see RFC 9180 §4:
 *   labeled_extract(salt, label, ikm) = Extract(salt, labeled_ikm)
 *   labeled_ikm = concat("HPKE-v1", suite_id, label, ikm)
 */
async function hkdfExtract(
    salt: Uint8Array,
    label: Uint8Array,
    ikm: Uint8Array,
    ikmId: Uint8Array,
): Promise<Uint8Array> {
    const labeledIkm = concatBuffers(
        new Uint8Array([0x48, 0x50, 0x4b, 0x45, 0x2d, 0x76, 0x31]), // "HPKE-v1"
        HPKE_SUITE_ID,
        label,
        ikm,
        ikmId,
    );

    // HKDF Extract using Web Crypto API
    const key = await crypto.subtle.importKey(
        "raw",
        salt.length > 0 ? salt : new Uint8Array(32), // RFC: if salt is empty, use string of Hash.length zeros
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"],
    );

    const prk = await crypto.subtle.sign("HMAC", key, labeledIkm);
    return new Uint8Array(prk);
}

/**
 * Simple HKDF Expand with HPKE labels.
 *
 *   labeled_expand(prk, label, info, L)
 *     = HKDF-Expand(prk, concat(uint16be(L), "HPKE-v1", suite_id, label, info), L)
 */
async function hkdfExpand(
    prk: Uint8Array,
    label: Uint8Array,
    info: Uint8Array,
    length: number,
): Promise<Uint8Array> {
    // RFC 9180 §4: labeled_info = concat(uint16(length), "HPKE-v1", suite_id, label, info)
    const lengthBytes = new Uint8Array(2);
    lengthBytes[0] = (length >> 8) & 0xff;
    lengthBytes[1] = length & 0xff;

    const labeledInfo = concatBuffers(
        lengthBytes,
        new Uint8Array([0x48, 0x50, 0x4b, 0x45, 0x2d, 0x76, 0x31]), // "HPKE-v1"
        HPKE_SUITE_ID,
        label,
        info,
    );

    // HKDF Expand using Web Crypto API
    const key = await crypto.subtle.importKey(
        "raw",
        prk,
        { name: "HKDF" },
        false,
        ["deriveBits"],
    );

    const derived = await crypto.subtle.deriveBits(
        {
            name: "HKDF",
            hash: "SHA-256",
            salt: new Uint8Array(0), // Salt is already applied in Extract step
            info: labeledInfo,
        },
        key,
        length * 8,
    );

    return new Uint8Array(derived);
}

// ============================================================================
// Utility functions
// ============================================================================

async function sha256(data: Uint8Array): Promise<ArrayBuffer> {
    return crypto.subtle.digest("SHA-256", data);
}

function concatBuffers(...buffers: Uint8Array[]): Uint8Array {
    const totalLength = buffers.reduce((sum, b) => sum + b.length, 0);
    const result = new Uint8Array(totalLength);
    let offset = 0;
    for (const buf of buffers) {
        result.set(buf, offset);
        offset += buf.length;
    }
    return result;
}
