use crate::{AttError, AttResult, journal::JournalConfig, parameters::TlsParams};
use ewqwe_credential_verifier_ui::VerifierUiConfig;
use serde::{Deserialize, Serialize};
use std::{
    env, fs,
    path::{Path, PathBuf},
};
use tracing::info;

const LOCAL_CONFIG_FILE_NAME: &str = "credential-server.toml";
const PLATFORM_CONFIG_FILE_NAME: &str = "config.toml";
const EDITOR_CONFIG_DIR: &str = "ewQwe";
const APP_CONFIG_DIR: &str = "Credential Server";

#[derive(Clone, Debug, Deserialize, Serialize)]
/// The Forward Proxy Parameters
pub struct ServerParams {
    pub host_name: String,
    pub host_port: u16,
    pub tls_params: TlsParams,
    pub default_username: Option<String>,
    pub openid4vp_config: ewqwe_openid4vp::OpenID4VPServiceConfig,

    /// Logging/tracing configuration.
    #[serde(default)]
    pub tracing_config: ewqwe_logging::TracingConfig,

    /// Legacy/shortcut `rust_log` string for compatibility with existing config format.
    /// If both `rust_log` and `tracing_config.rust_log` are provided, the nested configuration wins.
    #[serde(default)]
    pub rust_log: Option<String>,

    /// If true, skip requiring client certificate authentication and use a default
    /// authenticated user for all requests.
    #[serde(default)]
    pub disable_authentication: bool,

    /// Username to insert into request context when `disable_authentication=true`.
    /// Defaults to "test" when omitted.
    #[serde(default)]
    pub disabled_authentication_user: Option<String>,

    /// Directory containing CA certificates used to verify credential issuers.
    /// All `*.pem` files in this directory are loaded as trusted CA anchors.
    /// Credentials whose issuer JWT `x5c` chain (SD-JWT) or mDoc `issuerAuth` chain
    /// terminates at a CA in this directory are considered trustworthy.
    /// Defaults to `issuers_cas/` in the same directory as the config file.
    ///
    /// NOTE: This directory is loaded at startup and cached. Restart the server
    /// to apply changes after adding/removing certs.
    #[serde(default)]
    pub issuers_cas_dir: Option<String>,

    /// Path to the PEM certificate whose public key is used to verify signed
    /// attestation JWTs.  The `iss` claim is set to the CN of the certificate's
    /// Subject Name.  Resolved relative to the config file directory.
    /// Defaults to `tls_params.server_certificate` when not set.
    #[serde(default)]
    pub attestation_issuer_certificate: Option<String>,

    /// Path to the PEM private key used to sign attestation JWTs.
    /// Resolved relative to the config file directory.
    /// Defaults to `tls_params.server_private_key` if not set.
    #[serde(default)]
    pub attestation_issuer_key: Option<String>,

    /// Verification journal configuration.
    ///
    /// When present and `enabled = true`, every successful attestation is
    /// recorded in an append-only, hash-chained journal.
    /// Omit or set `enabled = false` to disable journaling.
    #[serde(default)]
    pub journal_config: JournalConfig,

    /// Public root URL of this server, used when building wallet callback URIs
    /// (e.g. `response_uri` / `request_uri` in OpenID4VP flows generated by the
    /// Verifier App).
    ///
    /// Set this when the server is behind a reverse proxy, NAT, or the bind
    /// address (`0.0.0.0`) differs from the address reachable by wallets.
    ///
    /// Example: `"https://demo.ewqwe.local:9443"` or `"https://verifier.example.com"`.
    ///
    /// Priority when building the QR code public URL:
    ///   1. `[verifier_ui].qr_code_callback_url` (most specific override)
    ///   2. This field (`public_root_url`)
    ///   3. URL inferred from the incoming HTTP request (last resort)
    #[serde(default)]
    pub public_root_url: Option<String>,

    /// Verifier App configuration.
    ///
    /// When `enabled = true`, the embedded web application for QR-code-based
    /// age verification is activated and all `/verifier_ui/*` routes are served.
    /// Omit or set `enabled = false` (the default) to disable the app.
    #[serde(default, rename = "verifier_ui")]
    pub verifier_ui_config: VerifierUiConfig,
}

impl ServerParams {
    pub fn load_from_default_locations() -> AttResult<(Self, PathBuf)> {
        let search_paths = Self::default_config_search_paths()?;

        let config_path = search_paths
            .iter()
            .find(|path| path.is_file())
            .cloned()
            .ok_or_else(|| {
                AttError::Config(format!(
                    "No configuration file found. Searched: {}",
                    search_paths
                        .iter()
                        .map(|path| path.display().to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                ))
            })?;

        info!("Loading configuration from {}", config_path.display());

        let params = Self::load_from_file(&config_path)?;
        Ok((params, config_path))
    }

    pub fn load_from_file(path: impl AsRef<Path>) -> AttResult<Self> {
        let path = path.as_ref();
        let config = fs::read_to_string(path).map_err(|error| {
            AttError::Config(format!(
                "Failed to read configuration file {}: {error}",
                path.display()
            ))
        })?;

        let mut params: Self = toml::from_str(&config).map_err(|error| {
            AttError::Config(format!(
                "Failed to parse configuration file {}: {error}",
                path.display()
            ))
        })?;

        // Allow top-level rust_log to shadow tracing_config.rust_log for backward compatibility.
        if params.tracing_config.rust_log.is_none()
            && let Some(rust_log) = params.rust_log.take()
        {
            params.tracing_config.rust_log = Some(rust_log);
        }

        // Ensure optional tracing config gets defaults.
        // Do not overwrite explicit values set by config, especially rust_log.
        if params.tracing_config.service_name.is_empty() {
            params.tracing_config.service_name = "credential_verifier".to_string();
        }

        // Keep defaults for other optionals only if not set.
        let default_tracing = ewqwe_logging::TracingConfig::default();
        if params.tracing_config.otlp.is_none() {
            params.tracing_config.otlp = default_tracing.otlp;
        }

        let base_dir = path.parent().unwrap_or_else(|| Path::new("."));
        params.resolve_relative_paths(base_dir);

        // Set the UI qr_code_callback_url to the public_root_url if not set.
        if params.verifier_ui_config.qr_code_callback_url.is_none() {
            params.verifier_ui_config.qr_code_callback_url = params.public_root_url.clone();
        }

        Ok(params)
    }

    fn default_config_search_paths() -> AttResult<Vec<PathBuf>> {
        Ok(vec![
            env::current_dir()
                .map_err(|error| {
                    AttError::Config(format!("Failed to determine current directory: {error}"))
                })?
                .join(LOCAL_CONFIG_FILE_NAME),
            Self::platform_config_dir()?.join(PLATFORM_CONFIG_FILE_NAME),
        ])
    }

    fn platform_config_dir() -> AttResult<PathBuf> {
        #[cfg(target_os = "windows")]
        {
            env::var_os("APPDATA")
                .map(PathBuf::from)
                .ok_or_else(|| {
                    AttError::Config("APPDATA is not set; cannot resolve config directory".into())
                })
                .map(|base| base.join(EDITOR_CONFIG_DIR).join(APP_CONFIG_DIR))
        }

        #[cfg(target_os = "macos")]
        {
            env::var_os("HOME")
                .map(PathBuf::from)
                .ok_or_else(|| {
                    AttError::Config("HOME is not set; cannot resolve config directory".into())
                })
                .map(|home| {
                    home.join("Library")
                        .join("Application Support")
                        .join(EDITOR_CONFIG_DIR)
                        .join(APP_CONFIG_DIR)
                })
        }

        #[cfg(all(unix, not(target_os = "macos")))]
        {
            let base = env::var_os("XDG_CONFIG_HOME")
                .map(PathBuf::from)
                .or_else(|| env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))
                .ok_or_else(|| {
                    AttError::Config(
                        "Neither XDG_CONFIG_HOME nor HOME is set; cannot resolve config directory"
                            .into(),
                    )
                })?;

            Ok(base.join(EDITOR_CONFIG_DIR).join(APP_CONFIG_DIR))
        }
    }

    fn resolve_relative_paths(&mut self, base_dir: &Path) {
        self.tls_params.server_private_key =
            resolve_path(base_dir, &self.tls_params.server_private_key);
        self.tls_params.server_certificate =
            resolve_path(base_dir, &self.tls_params.server_certificate);
        self.tls_params.server_ca_chain = resolve_path(base_dir, &self.tls_params.server_ca_chain);

        if let Some(client_ca_cert_chain) = &mut self.tls_params.client_ca_cert_chain {
            *client_ca_cert_chain = resolve_path(base_dir, client_ca_cert_chain);
        }

        if let Some(haip_config) = &mut self.openid4vp_config.haip_config {
            haip_config.x509_cert_path = resolve_path(base_dir, &haip_config.x509_cert_path);
            haip_config.x509_key_path = resolve_path(base_dir, &haip_config.x509_key_path);
        }

        // Resolve credential issuer CA directory (default: issuers_cas/)
        let default_dir = "issuers_cas";
        let dir = self.issuers_cas_dir.as_deref().unwrap_or(default_dir);
        info!(
            "Resolving credential issuer CA directory: base_dir='{}', dir='{}'",
            base_dir.display(),
            dir
        );
        self.issuers_cas_dir = Some(resolve_path(base_dir, dir));

        if let Some(cert_path) = &mut self.attestation_issuer_certificate {
            *cert_path = resolve_path(base_dir, cert_path);
        }

        if let Some(key_path) = &mut self.attestation_issuer_key {
            *key_path = resolve_path(base_dir, key_path);
        }

        // Resolve the SQLite file path in the journal config if present.
        if let crate::journal::JournalBackend::SqliteFile { path } =
            &mut self.journal_config.backend
        {
            *path = resolve_path(base_dir, path);
        }
    }
}

impl ServerParams {
    pub fn credential_issuer_ca_dir(&self) -> &str {
        self.issuers_cas_dir.as_deref().unwrap_or("issuers_cas")
    }

    /// Username to use when authentication is disabled.
    pub fn disabled_authentication_user(&self) -> &str {
        self.disabled_authentication_user
            .as_deref()
            .unwrap_or("test")
    }

    /// Path to the PEM certificate for attestation JWT verification.
    /// Falls back to [`TlsParams::server_certificate`] when not configured.
    pub fn attestation_issuer_certificate_path(&self) -> &str {
        self.attestation_issuer_certificate
            .as_deref()
            .unwrap_or(self.tls_params.server_certificate.as_str())
    }

    /// Construct tracing configuration to use for initialization.
    /// Returns a copy of the configured tracing settings.
    pub fn tracing_config(&self) -> ewqwe_logging::TracingConfig {
        self.tracing_config.clone()
    }

    /// Issuer identifier for the `iss` claim — the CN from the attestation signing certificate.
    ///
    /// Reads `attestation_issuer_certificate` (or falls back to
    /// `tls_params.server_certificate`) and extracts the Subject CN.
    pub fn attestation_issuer_iss(&self) -> AttResult<String> {
        use openssl::nid::Nid;
        use openssl::x509::X509;

        let cert_path = self.attestation_issuer_certificate_path();
        let cert_pem = std::fs::read(cert_path).map_err(|e| {
            AttError::Config(format!(
                "Failed to read attestation issuer certificate '{cert_path}': {e}"
            ))
        })?;
        let cert = X509::from_pem(&cert_pem).map_err(|e| {
            AttError::Config(format!(
                "Failed to parse attestation issuer certificate '{cert_path}': {e}"
            ))
        })?;
        cert.subject_name()
            .entries_by_nid(Nid::COMMONNAME)
            .next()
            .and_then(|e| e.data().as_utf8().ok())
            .map(|cn| cn.to_string())
            .ok_or_else(|| {
                AttError::Config(format!(
                    "No CN found in attestation issuer certificate subject: {cert_path}"
                ))
            })
    }

    /// RFC 7638 JWK thumbprint of the attestation signing certificate's public key.
    ///
    /// Used as the `kid` in both the JWKS and the signed attestation JWT header
    /// so the verifier can locate the right key without ambiguity.
    pub fn attestation_issuer_kid(&self) -> Option<String> {
        use base64::Engine as _;
        use openssl::x509::X509;

        let cert_path = self.attestation_issuer_certificate_path();
        let cert_pem = std::fs::read(cert_path).ok()?;
        let cert = X509::from_pem(&cert_pem).ok()?;
        let cert_der = cert.to_der().ok()?;
        let fingerprint = openssl::sha::sha256(&cert_der);
        Some(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(fingerprint))
    }

    /// Path to the PEM private key for signing attestation JWTs.
    /// Falls back to [`TlsParams::server_private_key`] when not configured.
    pub fn attestation_issuer_key_path(&self) -> &str {
        self.attestation_issuer_key
            .as_deref()
            .unwrap_or(self.tls_params.server_private_key.as_str())
    }
}

fn resolve_path(base_dir: &Path, value: &str) -> String {
    let path = Path::new(value);
    if path.is_absolute() {
        value.to_string()
    } else {
        base_dir.join(path).display().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::ServerParams;
    use ewqwe_logging::TracingConfig;
    use std::{fs, path::PathBuf};
    use uuid::Uuid;

    #[test]
    fn loads_toml_and_resolves_relative_paths_from_config_directory() {
        let temp_dir =
            std::env::temp_dir().join(format!("credential-server-config-test-{}", Uuid::new_v4()));

        fs::create_dir_all(&temp_dir).expect("failed to create temp config directory");

        let config_path = temp_dir.join("credential-server.toml");
        fs::write(
            &config_path,
            r#"
host_name = "127.0.0.1"
host_port = 9443
default_username = "demo-user"

[tls_params]
server_private_key = "certs/server.key.pem"
server_certificate = "certs/server.cert.pem"
server_ca_chain = "certs/ca.chain.pem"
client_ca_cert_chain = "certs/client-ca.pem"

[openid4vp_config]
transaction_ttl_secs = 300
trusted_issuer_certs_dir = "issuers"

[openid4vp_config.haip_config]
x509_cert_path = "certs/server.fullchain.pem"
x509_key_path = "certs/server.key.pem"
"#,
        )
        .expect("failed to write config file");

        let params = ServerParams::load_from_file(&config_path).expect("failed to load config");

        assert_eq!(params.host_name, "127.0.0.1");
        assert_eq!(params.host_port, 9443);
        assert_eq!(
            PathBuf::from(&params.tls_params.server_private_key),
            temp_dir.join("certs/server.key.pem")
        );
        assert_eq!(
            PathBuf::from(&params.tls_params.server_certificate),
            temp_dir.join("certs/server.cert.pem")
        );
        assert_eq!(
            PathBuf::from(
                params
                    .openid4vp_config
                    .haip_config
                    .as_ref()
                    .expect("missing haip config")
                    .x509_cert_path
                    .as_str(),
            ),
            temp_dir.join("certs/server.fullchain.pem")
        );
        assert_eq!(
            params.credential_issuer_ca_dir(),
            temp_dir.join("issuers_cas").display().to_string()
        );

        fs::remove_dir_all(&temp_dir).expect("failed to remove temp config directory");
    }

    #[test]
    fn loads_toml_with_tracing_config() {
        let temp_dir =
            std::env::temp_dir().join(format!("credential-server-config-test-{}", Uuid::new_v4()));
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");

        let config_path = temp_dir.join("credential-server.toml");
        fs::write(
            &config_path,
            r#"
host_name = "127.0.0.1"
host_port = 9443

[tls_params]
server_private_key = "certs/server.key.pem"
server_certificate = "certs/server.cert.pem"
server_ca_chain = "certs/ca.chain.pem"

[openid4vp_config]
transaction_ttl_secs = 300

[tracing_config]
rust_log = "info,actix_server=warn"
"#,
        )
        .expect("failed to write config file");

        let params = ServerParams::load_from_file(&config_path).expect("failed to load config");
        assert_eq!(
            params.tracing_config().rust_log.as_deref(),
            Some("info,actix_server=warn")
        );

        fs::remove_dir_all(&temp_dir).expect("failed to remove temp config directory");
    }

    #[test]
    fn loads_toml_with_public_root_url() {
        let temp_dir =
            std::env::temp_dir().join(format!("credential-server-config-test-{}", Uuid::new_v4()));
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");

        let config_path = temp_dir.join("credential-server.toml");
        fs::write(
            &config_path,
            r#"
host_name = "127.0.0.1"
host_port = 9443
public_root_url = "https://ewqwe.example.com"

[tls_params]
server_private_key = "certs/server.key.pem"
server_certificate = "certs/server.cert.pem"
server_ca_chain = "certs/ca.chain.pem"

[openid4vp_config]
transaction_ttl_secs = 300

[tracing_config]
rust_log = "info,actix_server=warn"
"#,
        )
        .expect("failed to write config file");

        let params = ServerParams::load_from_file(&config_path).expect("failed to load config");

        assert_eq!(
            params.public_root_url.as_deref(),
            Some("https://ewqwe.example.com")
        );

        assert_eq!(
            params.verifier_ui_config.qr_code_callback_url.as_deref(),
            Some("https://ewqwe.example.com")
        );
    }

    #[test]
    fn loads_credential_server_toml_from_project() {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let config_path = manifest_dir.join("credential-server.toml");
        let params = ServerParams::load_from_file(config_path)
            .expect("failed to load credential-server.toml");

        assert_eq!(
            params.tracing_config().rust_log.as_deref(),
            Some("info,credential_verifier=debug,ewqwe_openid4vp=debug")
        );
        assert!(params.disable_authentication);
        assert_eq!(params.disabled_authentication_user(), "local_tests_user");

        assert_eq!(
            PathBuf::from(&params.tls_params.server_private_key),
            manifest_dir.join("../certificates/tls/ewqwe.server.key.pem")
        );
        assert_eq!(
            PathBuf::from(&params.tls_params.server_certificate),
            manifest_dir.join("../certificates/tls/ewqwe.server.cert.pem")
        );
        assert_eq!(
            PathBuf::from(&params.tls_params.server_ca_chain),
            manifest_dir.join("../certificates/tls/ewqwe.ca.pem")
        );
    }

    #[test]
    fn loads_toml_without_tracing_config_uses_default() {
        let temp_dir =
            std::env::temp_dir().join(format!("credential-server-config-test-{}", Uuid::new_v4()));
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");

        let config_path = temp_dir.join("credential-server.toml");
        fs::write(
            &config_path,
            r#"
host_name = "127.0.0.1"
host_port = 9443

[tls_params]
server_private_key = "certs/server.key.pem"
server_certificate = "certs/server.cert.pem"
server_ca_chain = "certs/ca.chain.pem"

[openid4vp_config]
transaction_ttl_secs = 300
"#,
        )
        .expect("failed to write config file");

        let params = ServerParams::load_from_file(&config_path).expect("failed to load config");
        assert!(params.tracing_config().rust_log.is_none());

        fs::remove_dir_all(&temp_dir).expect("failed to remove temp config directory");
    }

    #[test]
    fn loads_toml_with_qr_code_callback_url() {
        let temp_dir =
            std::env::temp_dir().join(format!("credential-server-config-test-{}", Uuid::new_v4()));
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");

        let config_path = temp_dir.join("credential-server.toml");
        fs::write(
            &config_path,
            r#"
host_name = "127.0.0.1"
host_port = 9443
public_root_url = "https://ewqwe.example.com"


[tls_params]
server_private_key = "certs/server.key.pem"
server_certificate = "certs/server.cert.pem"
server_ca_chain = "certs/ca.chain.pem"

[openid4vp_config]
transaction_ttl_secs = 300

[tracing_config]
rust_log = "info,actix_server=warn"

[verifier_ui]
qr_code_callback_url = "https://modified.example.com/"
"#,
        )
        .expect("failed to write config file");

        let params = ServerParams::load_from_file(&config_path).expect("failed to load config");

        assert_eq!(
            params.public_root_url.as_deref(),
            Some("https://ewqwe.example.com")
        );

        assert_eq!(
            params.verifier_ui_config.qr_code_callback_url.as_deref(),
            Some("https://modified.example.com/")
        );
    }

    #[test]
    fn server_params_enable_disable_authentication_defaults() {
        let params = ServerParams {
            host_name: "127.0.0.1".to_string(),
            host_port: 9443,
            tls_params: crate::parameters::TlsParams::default(),
            default_username: None,
            rust_log: None,
            public_root_url: None,
            openid4vp_config: ewqwe_openid4vp::OpenID4VPServiceConfig {
                transaction_ttl_secs: None,
                haip_config: None,
                transaction_store: Default::default(),
            },
            disable_authentication: false,
            disabled_authentication_user: None,
            issuers_cas_dir: None,
            attestation_issuer_certificate: None,
            attestation_issuer_key: None,
            journal_config: crate::journal::JournalConfig::default(),
            verifier_ui_config: crate::ewqwe_credential_verifier_ui::VerifierUiConfig::default(),
            tracing_config: TracingConfig::default(),
        };

        assert!(!params.disable_authentication);
        assert_eq!(params.disabled_authentication_user(), "test");
        assert!(params.tracing_config.rust_log.is_none());
    }

    #[test]
    fn server_params_tracing_config_override() {
        let params = ServerParams {
            host_name: "127.0.0.1".to_string(),
            host_port: 9443,
            tls_params: crate::parameters::TlsParams::default(),
            default_username: None,
            rust_log: None,
            public_root_url: None,
            openid4vp_config: ewqwe_openid4vp::OpenID4VPServiceConfig {
                transaction_ttl_secs: None,
                haip_config: None,
                transaction_store: Default::default(),
            },
            tracing_config: ewqwe_logging::TracingConfig {
                rust_log: Some("info,actix_server=warn".to_string()),
                ..Default::default()
            },
            disable_authentication: false,
            disabled_authentication_user: None,
            issuers_cas_dir: None,
            attestation_issuer_certificate: None,
            attestation_issuer_key: None,
            journal_config: crate::journal::JournalConfig::default(),
            verifier_ui_config: crate::ewqwe_credential_verifier_ui::VerifierUiConfig::default(),
        };

        assert_eq!(
            params.tracing_config().rust_log.as_deref(),
            Some("info,actix_server=warn")
        );
    }
}
