//! ISO 18013-7 Annex C / W3C Digital Credentials API verification endpoint.
//!
//! This endpoint receives an already-decrypted mDoc DeviceResponse from the
//! Relying Party (which performs HPKE decryption in the browser) and verifies
//! the mDoc signature chain against trusted issuer CAs.
//!
//! ## Relationship to the existing `/verify` endpoint
//!
//! | Aspect         | `/verify` (OpenID4VP)                  | `/dc_api/verify` (DC API)             |
//! |----------------|----------------------------------------|---------------------------------------|
//! | Transport      | VP Token from wallet via direct_post   | Decrypted DeviceResponse from browser |
//! | Encryption     | Optional JWE (HAIP)                    | HPKE handled by RP in browser         |
//! | Nonce binding  | Server-stored nonce via transaction    | Nonce passed in request body          |
//! | State/tx mgmt  | OpenID4VP transaction state            | No transaction — stateless            |
//! | Credential     | mDoc or SD-JWT                         | mDoc only                            |
//!
//! Per the EU Age Verification Profile (Annex A of the AV spec, §A.5):
//! "The default method for the presentation of a Proof of Age attestation is
//!  the W3C Digital Credentials API. The W3C Digital Credentials API is used
//!  as specified in [ISO/IEC 18013-7], Annex C."

use actix_web::{HttpMessage, HttpRequest, HttpResponse, web};
use openssl::x509::X509;
use std::sync::Arc;
use tracing;

use crate::AttError;
use crate::authenticated_user::AuthenticatedUser;
use crate::journal::DynJournalStore;
use crate::journal::append_verification;
use crate::parameters::ServerParams;
use crate::server::verify_endpoint::create_attestation;
use ewqwe_digital_credential::verify_mdoc_presentation;
use ewqwe_openid4vp::{VerificationDetails, VerifyCredentialResponse};

/// Request body for the DC API verification endpoint.
#[derive(Debug, serde::Deserialize)]
pub struct DcApiVerifyRequest {
    /// Base64url-encoded (no pad), **already-decrypted** mDoc DeviceResponse CBOR.
    pub device_response_b64: String,

    /// The nonce generated by the RP and included in the `encryptionInfo`.
    /// Used for replay prevention — the verifier checks this matches
    /// what was sent in the request.
    pub nonce: String,

    /// RP identity (e.g. the verifier's public URL or certificate hash).
    /// Used in the attestation `aud` claim.
    pub client_id: String,

    /// Expected document type (e.g. "eu.europa.ec.av.1").
    /// The verifier checks the presented mDoc matches this type.
    #[serde(default)]
    pub doc_type: Option<String>,
}

/// Verify a DC API credential presentation (ISO 18013-7 Annex C).
///
/// # Request
///
/// ```json
/// {
///     "device_response_b64": "...",
///     "nonce": "n-0S6_WzA2Mj",
///     "client_id": "https://rp.example.com",
///     "doc_type": "eu.europa.ec.av.1"
/// }
/// ```
///
/// # Response
///
/// ```json
/// {
///     "success": true,
///     "message": "Credential verified",
///     "verification_details": {
///         "signature_valid": true,
///         "not_expired": true,
///         "issuer_trusted": true
///     },
///     "attestation": "..."
/// }
/// ```
pub async fn verify_dc_api(
    req: HttpRequest,
    body: web::Json<DcApiVerifyRequest>,
    server_params: web::Data<Arc<ServerParams>>,
    trusted_cas: web::Data<Arc<Vec<X509>>>,
    journal: Option<web::Data<Arc<DynJournalStore>>>,
) -> Result<HttpResponse, AttError> {
    let username = req
        .extensions()
        .get::<AuthenticatedUser>()
        .map(|u| u.username.clone())
        .ok_or_else(|| {
            AttError::Authentication(
                "mTLS authentication required: authenticated user not found".to_string(),
            )
        })?;

    tracing::debug!(
        client_id = %body.client_id,
        nonce = %body.nonce,
        doc_type = ?body.doc_type,
        "DC API verify request received"
    );

    // --- Step 1: Verify the mDoc DeviceResponse ---
    // The DeviceResponse was already HPKE-decrypted by the RP in the browser.
    // We use the nonce as the expected nonce for the mDoc verification.
    let response_uri = &body.client_id; // For DC API, client_id serves as response_uri

    let mdoc_result = verify_mdoc_presentation(
        &body.device_response_b64,
        &body.client_id,
        &body.nonce,
        response_uri,
        false, // DC API uses direct mode, not JWT
        None,  // No JWK thumbprint needed for DC API
        trusted_cas.as_ref(),
    )
    .map_err(|e| AttError::BadRequest(format!("mDoc presentation verification failed: {e}")))?;

    // --- Step 2: Check doc_type matches if specified ---
    if let Some(ref expected_doc_type) = body.doc_type {
        if mdoc_result.doc_type != *expected_doc_type {
            return Err(AttError::BadRequest(format!(
                "Document type mismatch: expected {}, got {}",
                expected_doc_type, mdoc_result.doc_type
            )));
        }
    }

    // --- Step 3: Check verification result ---
    if !mdoc_result.issuer_trusted {
        tracing::warn!(
            doc_type = %mdoc_result.doc_type,
            "mDoc issuer certificate is not trusted"
        );
        let errors = vec!["mDoc issuerAuth certificate chain is not trusted".to_string()];

        // Still create an attestation with failure info
        let transaction_id = uuid::Uuid::new_v4().to_string();
        let attestation = create_attestation(
            &body.client_id,
            Some(&body.nonce),
            &transaction_id,
            &mdoc_result.claims,
            &mdoc_result.doc_type,
            &mdoc_result.namespace,
            &server_params,
        )?;

        return Ok(HttpResponse::Ok().json(VerifyCredentialResponse {
            success: false,
            message: "Credential verification failed: issuer not trusted".to_string(),
            verification_details: Some(VerificationDetails {
                signature_valid: true,
                not_expired: mdoc_result.not_expired,
                issuer_trusted: false,
            }),
            attestation,
            errors: Some(errors),
        }));
    }

    if !mdoc_result.not_expired {
        tracing::warn!(
            doc_type = %mdoc_result.doc_type,
            "mDoc credential has expired"
        );
        let errors = vec!["mDoc credential has expired: MSO validUntil is in the past".to_string()];

        let transaction_id = uuid::Uuid::new_v4().to_string();
        let attestation = create_attestation(
            &body.client_id,
            Some(&body.nonce),
            &transaction_id,
            &mdoc_result.claims,
            &mdoc_result.doc_type,
            &mdoc_result.namespace,
            &server_params,
        )?;

        return Ok(HttpResponse::Ok().json(VerifyCredentialResponse {
            success: false,
            message: "Credential verification failed: credential expired".to_string(),
            verification_details: Some(VerificationDetails {
                signature_valid: true,
                not_expired: false,
                issuer_trusted: true,
            }),
            attestation,
            errors: Some(errors),
        }));
    }

    // --- Step 4: Create attestation on success ---
    let transaction_id = uuid::Uuid::new_v4().to_string();
    let attestation = create_attestation(
        &body.client_id,
        Some(&body.nonce),
        &transaction_id,
        &mdoc_result.claims,
        &mdoc_result.doc_type,
        &mdoc_result.namespace,
        &server_params,
    )?;

    tracing::info!(
        doc_type = %mdoc_result.doc_type,
        namespace = %mdoc_result.namespace,
        client_id = %body.client_id,
        "DC API credential verified successfully"
    );

    // --- Step 5: Record in journal if enabled ---
    if let Some(journal_store) = &journal {
        let summary = serde_json::json!({
            "success": true,
            "credential_claims": &mdoc_result.claims,
            "doc_type": &mdoc_result.doc_type,
            "namespace": &mdoc_result.namespace,
        });

        if let Err(e) = append_verification(
            journal_store.as_ref().as_ref(),
            &username,
            &attestation,
            None, // no JTI extraction for DC API flow
            Some(&body.client_id),
            Some(&mdoc_result.doc_type),
            Some(&mdoc_result.namespace),
            summary,
            None, // no QR user mapping
            None,
        )
        .await
        {
            tracing::error!(error = %e, "failed to append to verification journal");
            return Err(AttError::from(e));
        }
    }

    Ok(HttpResponse::Ok().json(VerifyCredentialResponse {
        success: true,
        message: "Credential verified successfully".to_string(),
        verification_details: Some(VerificationDetails {
            signature_valid: true,
            not_expired: true,
            issuer_trusted: true,
        }),
        attestation,
        errors: None,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test that the request struct deserializes correctly.
    #[test]
    fn test_dc_api_verify_request_deserialization() {
        let json = serde_json::json!({
            "device_response_b64": "dGVzdA",
            "nonce": "n-0S6_WzA2Mj",
            "client_id": "https://rp.example.com",
            "doc_type": "eu.europa.ec.av.1"
        });

        let req: DcApiVerifyRequest = serde_json::from_value(json).unwrap();
        assert_eq!(req.device_response_b64, "dGVzdA");
        assert_eq!(req.nonce, "n-0S6_WzA2Mj");
        assert_eq!(req.client_id, "https://rp.example.com");
        assert_eq!(req.doc_type, Some("eu.europa.ec.av.1".to_string()));
    }

    /// Test that doc_type is optional.
    #[test]
    fn test_dc_api_verify_request_no_doc_type() {
        let json = serde_json::json!({
            "device_response_b64": "dGVzdA",
            "nonce": "n-0S6_WzA2Mj",
            "client_id": "https://rp.example.com"
        });

        let req: DcApiVerifyRequest = serde_json::from_value(json).unwrap();
        assert!(req.doc_type.is_none());
    }
}
