[package]
name = "ewqwe_credential_verifier_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Digital Credential Verifier Server"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ewqwe_credential_verifier_server"
path = "src/main.rs"


[dependencies]
alcoholic_jwt = { workspace = true }
actix-cors = { workspace = true }
actix-identity = { workspace = true }
actix-files = { workspace = true }
actix-session = { workspace = true }
argon2 = { workspace = true }
actix-service = { workspace = true }
actix-tls = { workspace = true }
actix-web = { workspace = true, features = ["macros", "openssl"] }
base64 = "0.22"
chrono = { workspace = true }
ciborium = { workspace = true }
coset = { workspace = true }
ewqwe_digital_credential = { workspace = true }
ewqwe_credential_verifier_ui = { workspace = true }
ewqwe_logging = { workspace = true }
ewqwe_openid4vp = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
openssl = { workspace = true, features = ["vendored"] }
reqwest = { workspace = true, features = [
    "json",
    "native-tls",
    "http2",
    "cookies",
] }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
cookie_store = { workspace = true }
ewqwe_digital_identity = { workspace = true, features = ["default-tls"] }
openssl = { workspace = true, features = ["vendored"] }
