[package]
name = "credential_verifier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "API Server"

[lib]
path = "src/lib.rs"

[features]
default = ["openssl"]
openssl = ["actix-web/openssl", "dep:openssl"]
rustls = ["actix-web/rustls-0_23", "dep:rustls"]
# no_jwt_validation: only useful for tests, do not enable in production
# this feature will disable JWT verification of the token issuer and expiration date
no_jwt_validation = []

[dependencies]
alcoholic_jwt = { workspace = true }
actix-cors = { workspace = true }
actix-identity = { workspace = true }
actix-files = { workspace = true }
actix-session = { workspace = true, features = [
    "cookie-session",
    "redis-session",
] }
actix-tls = { workspace = true }
actix-web = { workspace = true, features = ["macros"] }
base64 = "0.22"
chrono = { workspace = true }
ciborium = { workspace = true }
coset = { workspace = true }
ewqwe_logging = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
openssl = { workspace = true, features = ["vendored"], optional = true }
reqwest = { workspace = true, features = [
    "json",
    "native-tls",
    "http2",
    "cookies",
] }
rustls = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
cookie_store = { workspace = true }
openssl = { workspace = true, features = ["vendored"] }
tokio = { workspace = true }
toml = { workspace = true }
