# Credential Server Configuration used for testing and development. 
host_name = "0.0.0.0"
host_port = 9443
default_username = "demo-user"

[tls_params]
server_private_key = "src/tests/certificates/ec/ewqwe.server.key.pem"
server_certificate = "src/tests/certificates/ec/ewqwe.server.cert.pem"
server_ca_chain = "src/tests/certificates/ec/ewqwe.chain.pem"
client_ca_cert_chain = "src/tests/certificates/ec/ewqwe.chain.pem"

[openid4vp_config]
transaction_ttl_secs = 300

[openid4vp_config.haip_config]
x509_cert_path = "src/tests/certificates/ec/ewqwe.server.fullchain.pem"
x509_key_path = "src/tests/certificates/ec/ewqwe.server.key.pem"