[book]
title = "ewQwe Digital Identity"
authors = ["ewQwe Contributors"]
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-css = ["custom-theme.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
